config/routes.rb
Rails.application.routes.draw do
                     #don't use devise namespace for the callback, use omniauthcallbacks controller
  devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks"}

  resources :linkedin
  get '/linkedin_profile' => 'linkedin#linkedin_profile'
  get '/oauth_account' => 'linkedin#oauth_account'
  get '/linkedin_oauth_url' => 'linkedin#generate_linkedin_oauth_url'
  root :to => 'welcome#index'

  resources :listings, only: [:index, :create, :new, :destroy]
end

app/controllers/linkedin_controller.rb
class LinkedinController < ApplicationController
  before_filter :authenticate_user!
  before_action :get_basic_profile

  @@config = {
    :site => 'https://api.linkedin.com',
    :authorize_path => '/uas/oauth/authenticate',
    :request_token_path => '/uas/oauth/requestToken?scope=r_basicprofile+r_fullprofile',
    :access_token_path => '/uas/oauth/accessToken'
  }

  def index
    unless LinkedinOauthSetting.find_by_user_id(current_user.id).nil?
    end
    oauth_account
  end

  def show
    @favorites = Favorite.where(user_id: current_user.id)
  end

  def linkedin_profile
    @favorites = Favorite.where(user_id: current_user.id)
  end

  def oauth_account
    @client = LinkedIn::Client.new(ENV["LINKEDIN_API_KEY"], ENV["LINKEDIN_SECRET"], @@config)
    pin = params[:oauth_verifier]
    if pin
      atoken, asecret = @client.authorize_from_request(session[:rtoken], session[:rsecret], pin)
      LinkedinOauthSetting.create!(:asecret => asecret, :atoken => atoken, :user_id => current_user.id)
    end
    redirect_to linkedin_path(current_user.id)
  end

  def generate_linkedin_oauth_url
    if LinkedinOauthSetting.find_by_user_id(current_user.id).nil?
      client = LinkedIn::Client.new(ENV["LINKEDIN_API_KEY"], ENV["LINKEDIN_SECRET"], @@config)
      request_token = client.request_token(:oauth_callback => "http://#{request.host}:#{request.port}/oauth_account")
      session[:rtoken] = request_token.token
      session[:rsecret] = request_token.secret
      redirect_to request_token.authorize_url
    else
      redirect_to "/oauth_account"
    end
  end

  def get_basic_profile
    client = get_client
    profile = client.profile(:fields => ["first-name", "last-name", "maiden-name", "formatted-name" ,:headline, :location, :industry, :summary, :specialties, "picture-url", "public-profile-url"])

    basic_profile = { formatted_name: "#{profile.first_name} #{profile.last_name}",
                      picture_url: profile.picture_url,
                      headline: profile.headline,
                      summary: profile.summary,
                      location: profile.location.name
                    }
    new_basic_profile = BasicProfile.find_or_create_by(basic_profile)
    new_basic_profile.user = current_user
    @basic_profile = new_basic_profile
  end

  private

  def get_client
    linkedin_oauth_setting = LinkedinOauthSetting.find_by_user_id(current_user.id)
    client = LinkedIn::Client.new(ENV["LINKEDIN_API_KEY"], ENV["LINKEDIN_SECRET"], @@config)
    client.authorize_from_access(linkedin_oauth_setting.atoken, linkedin_oauth_setting.asecret)
    client
  end
end

app/helpers/linkedin_helper.rb
module LinkedinHelper
end

app/views/linkedin/index.html.erb
 <div class="page-wrapper">
  <section id="hero" class="hero-fixed hero-fade hero-medium">
    <div class="hero-wrap-outer">
      <div class="container">
        <div class="hero-wrap-inner">
                  </div>
      </div>
    </div>
  </section>

  <div class="container hero-content ">
    <div class="row-fluid product-hero" data-analytics-section="hero">

      <div class="span6 logged-out-left-hero-content">
        <h1 id="page-title">Link<span class="title">Up</span></h1>
        <h2 id="page-tag">Because Companies are People, too.</h2>
      </div>

        <div id="hero-custom-content" class="device-image-right">
          <%= image_tag "splash.png", alt: "splash image", class: "splash-image" %>
        </div>
    </div>
  </div>
</div><!-- .page-wrapper -->

<footer class="footer-container">

  <div class="listings-enter">
    <% if current_user %>
      <%= button_to "Let's Mingle", listings_path, method: 'get', class: "btn listings-btn btn-group-lg" %>
    <% end %>
  </div>
  <footer id="gaz-sub-footer" class="row-fluid">
    <div class="container">
      <div class="d-block d-block-helper-tfw g-helper-tfw-tweet-count-button">
          <iframe id="twitter-widget-0" scrolling="no" frameborder="0" allowtransparency="true" src="https://platform.twitter.com/widgets/tweet_button.1404859412.html#_=1405472533458&amp;count=horizontal&amp;id=twitter-widget-0&amp;lang=en&amp;original_referer=https%3A%2F%2Frichardhessler.%2F&amp;size=l&amp;text=LinkUp%20is%20the%20best%20app%20for%20jobs%20and%20was%20produced%20by%20@RJHessler%20from%20@GA_DC&amp;url=https%3A%2F%2Flinkup.herokuapp.com%2F" class="twitter-share-button twitter-tweet-button twitter-share-button twitter-count-horizontal" title="Twitter Tweet Button" data-twttr-rendered="true" style="width: 138px; height: 28px;">
        </iframe>
      </div>
    </div>

<footer id="globalfooter" class="row-fluid">
    <div class="container">
     <span class="copyright">© 2014 Richard Hessler</span>
    </div>
  </footer>
</footer>

app/views/linkedin/linkedin_profile.html.erb
<div class="row">
  <div class="span4">
    <div class="thumbnail">
      <img src="<%= @basic_profile.picture_url %>" style="float: left;margin: 5px;">
      <h3><%= @basic_profile.formatted_name %></h3>
      <h4><%= @basic_profile.headline %></h4>
      <br>
      <p><%= @basic_profile.summary %></p>
    </div>
  </div>
</div>

app/views/linkedin/show.html.erb
<div class="row">
  <div class="profile thumbnail col-lg-3">
    <img src="<%= @basic_profile.picture_url %>" style="float: left;margin: 5px;">
    <h3><%= @basic_profile.formatted_name %></h3>
    <h4><%= @basic_profile.headline %></h4>
    <br>
    <p><%= @basic_profile.summary %></p>
  </div>

  <div class="saved-listings thumbnail col-lg-8">
    <% @favorites.each do |favorite| %>
    <div class="favorites">
      <h3><a href="<%=favorite.company_url%>"><%= favorite.title %></a></h3>
      <p><%=favorite.description %></p>
    </div>
    <% end %>
  </div>
</div>